namespace EliteModels.Enums {
    public enum EDGovernment {
        Unknown = 0,
        Anarchy = 1,
        Communism = 2,
        Confederacy = 3,
        Corporate = 4,
        Cooperative = 5,
        Democracy = 6,
        Dictatorship,
        Feudal,
        Imperial,
        Patronage,
        Colony,
        Prison_Colony,
        Theocracy,
        None,

    }

    public enum EDAllegiance {
        Unknown = 0,
        Alliance = 1,
        Anarchy = 2,
        Empire = 3,
        Federation = 4,
        Independent = 5,
        None = 6,
    }

    public enum EDState {
        Unknown = 0,
        None = 1,
        Boom,
        Bust,
        Civil_Unrest,
        Civil_War,
        Expansion,
        Lockdown,
        Outbreak,
        War,
    }

    public enum EDSecurity {
        Unknown = 0,
        Low,
        Medium,
        High,
    }

    public enum EDStationType {
        Unknown = 0,
        Civilian_Outpost = 1,
        Commercial_Outpost = 2,
        Coriolis_Starport = 3,
        Industrial_Outpost = 4,
        Military_Outpost = 5,
        Mining_Outpost = 6,
        Ocellus_Starport = 7,
        Orbis_Starport = 8,
        Scientific_Outpost = 9,
        Unsanctioned_Outpost = 10,
        Unknown_Outpost = 11,
        Unknown_Starport = 12,
    }

    public enum EDEconomy {
        Unknown = 0,
        Agriculture = 1,
        Extraction = 2,
        High_Tech = 3,
        Industrial = 4,
        Military = 5,
        Refinery = 6,
        Service = 7,
        Terraforming = 8,
        Tourism = 9,
        None = 10,

    }

    public enum EDCommodities {
        Unknown = 0,
        Advanced_Catalysers,
        Agri__Medicines,
        Algae,
        Aluminium,
        Animal_Meat,
        Animal_Monitors,
        Aquaponic_Systems,
        Atmospheric_Processors,
        Auto__Fabricators,
        Basic_Medicines,
        Battle_Weapons,
        Bauxite,
        Beer,
        Bertrandite,
        Beryllium,
        Bioreducing_Lichen,
        Biowaste,
        Chemical_Waste,
        Clothing,
        Cobalt,
        Coffee,
        Coltan,
        Combat_Stabilisers,
        Computer_Components,
        Consumer_Technology,
        Copper,
        Crop_Harvesters,
        Domestic_Appliances,
        Explosives,
        Fish,
        Food_Cartridges,
        Fruit_and_Vegetables,
        Gallite,
        Gallium,
        Gold,
        Grain,
        H___E____Suits,
        Hydrogen_Fuel,
        Imperial_Slaves,
        Indite,
        Indium,
        Land_Enrichment_Systems,
        Leather,
        Lepidolite,
        Liquor,
        Lithium,
        Marine_Equipment,
        Microbial_Furnaces,
        Mineral_Extractors,
        Mineral_Oil,
        Narcotics,
        Natural_Fabrics,
        Non__lethal_Weapons,
        Palladium,
        Performance_Enhancers,
        Personal_Weapons,
        Pesticides,
        Platinum,
        Polymers,
        Power_Generators,
        Progenitor_Cells,
        Reactive_Armour,
        Resonating_Separators,
        Robotics,
        Rutile,
        Scrap,
        Semiconductors,
        Silver,
        Slaves,
        Superconductors,
        Synthetic_Fabrics,
        Synthetic_Meat,
        Tantalum,
        Tea,
        Terrain_Enrichment_Systems,
        Titanium,
        Tobacco,
        Toxic_Waste,
        Uraninite,
        Uranium,
        Water_Purifiers,
        Wine,
        Lucan_Onion_Head,
        Limpet,
        Wuthielo_Ku_Froth,
        Antiquities,
        Painite,
        Onion_Head,
        Trinkets_Of_Hidden_Fortune,
    }

    public enum SystemStatusEnum {
        Unknown = 0,
        EDSC = 1,
        RedWizzard = 2,
        EDDiscovery = 3,
        EDDB = 4,
        Inhumierer = 5,
    }
}